### ISSUE TITLE
straight.el Installation Instructions

### ISSUE THREAD

**Issue by scs-kno** [rudi/p-mode#2]
To use [straight-el](https://github.com/radian-software/straight.el) the following worked:

```lisp
(setq p-override-pascal-file-type t)
(use-package p-mode
  :straight (:host github :repo "rudi/p-mode" :files ("*.el"))
  :ensure t
  :mode "\\.p\\'"
  :commands (p-mode))
```

Thank you for your efforts

**Comment by rudi** [comment]
Thanks!  Does it work without the `(setq p-override-pascal-file-type t)` as well?  I wonder if having the `:mode` clause in the use-package form is sufficient..

**Comment by scs-kno** [comment]
It was needed on my 27.1 emacs, maybe newer versions are different.

**Comment by rudi** [comment]
Ok thanks!  I don't use straight so will leave the instructions as-is :)

**Comment by scs-kno** [comment]
I just discovered a bug with this setting: the yasnippets won't load. See the following excerpt from `*Messages*`:

```
[yas] Check your `yas-snippet-dirs': $HOME/.emacs.d/straight/build/p-mode/snippets is not a directory
[yas] Snippets loaded with some errors.  Check *Messages*.
```

This works:

```elisp
(setq p-override-pascal-file-type t)
(use-package p-mode
  :straight (:host github :repo "rudi/p-mode" :files ("*.el" "snippets"))
  :ensure t
  :mode "\\.p\\'"
  :commands (p-mode))
```

**Comment by rudi** [comment]
Thanks for the update--I also submitted https://github.com/melpa/melpa/pull/8466 to fix the melpa recipe
